if  not exist "C:\Program Files (x86)\" goto NOWINDIR  
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_ASF_Trimmer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_ASFMuxer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_BMPPushSrc.Ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_CustomEncoder.dll"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_EditEngine.dll"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_FileWriter.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MediaJointer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MKVMuxer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MKVSplitter.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MP2TrimmerFA.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MP4Demuxer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MP4Muxer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_MPEG4TrimmerFA.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_OCXSlider.ocx"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_Trimmer.ax"
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\SMM_WavMux.ax"   
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\eavcdec_hd.ax"      
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\eavcenc_hd.ax"        
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\ElMIxReader.dll"       
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\em2vd.ax"       
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\em2venc_hd.ax"     
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\empegmux.ax"         
regsvr32 /s  "c:\Program Files (x86)\Common Files\SMM\empgdmx.ax"         
regsvr32 /s  "c:\Program Files (x86)\Common Files\VLC\axvlc.dll"
:NOWINDIR
if  exist "C:\Program Files (x86)\" goto NOWEND
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_ASF_Trimmer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_ASFMuxer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_BMPPushSrc.Ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_CustomEncoder.dll"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_EditEngine.dll"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_FileWriter.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MediaJointer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MKVMuxer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MKVSplitter.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MP2TrimmerFA.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MP4Demuxer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MP4Muxer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_MPEG4TrimmerFA.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_OCXSlider.ocx"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_Trimmer.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\SMM_WavMux.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\eavcdec_hd.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\eavcenc_hd.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\ElMIxReader.dll"
regsvr32 /s  "c:\Program Files\Common Files\SMM\em2vd.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\em2venc_hd.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\empegmux.ax"
regsvr32 /s  "c:\Program Files\Common Files\SMM\empgdmx.ax"
regsvr32 /s  "c:\Program Files\Common Files\VLC\axvlc.dll"
Environment.Exit()
:NOWEND