#ifndef LangIDs_Defined
#define LangIDs_Defined
const int g_nLangCount = 152;
static TCHAR *wcsLangID[g_nLangCount][2] = 
{
	{_T(""), _T("Default")},
	{_T("af"), _T("Afrikaans")},
	{_T("ar-ae"), _T("Arabic (U.A.E.)")},
	{_T("ar-bh"), _T("Arabic (Bahrain)")},
	{_T("ar-dz"), _T("Arabic (Algeria)")},
	{_T("ar-eg"),_T("Arabic (Egypt)")},
	{_T("ar-iq"),_T("Arabic (Iraq)")},
	{_T("ar-jo"),_T("Arabic (Jordan)")},
	{_T("ar-kw"),_T("Arabic (Kuwait)")},
	{_T("ar-lb"),_T("Arabic (Lebanon)")},
	{_T("ar-ly"),_T("Arabic (Libya)")},
	{_T("ar-ma"),_T("Arabic (Morocco)")},
	{_T("ar-om"),_T("Arabic (Oman)")},
	{_T("ar-qa"),_T("Arabic (Qatar)")},
	{_T("ar-sa"),_T("Arabic (Saudi Arabia)")},
	{_T("ar-sy"),_T("Arabic (Syria)")},
	{_T("ar-tn"),_T("Arabic (Tunisia)")},
	{_T("ar-ye"),_T("Arabic (Yemen)")},
	{_T("ar"),_T("Arabic")},
	{_T("as"),_T("Assamese")},
	{_T("az"),_T("Azeri")},
	{_T("be"),_T("Belarusian")},
	{_T("bg"),_T("Bulgarian")},
	{_T("bn"),_T("Bengali")},
	{_T("ca"),_T("Catalan")},
	{_T("cs"),_T("Czech")},
	{_T("da"),_T("Danish")},
	{_T("de-at"),_T("German (Austria)")},
	{_T("de-ch"),_T("German (Switzerland)")},
	{_T("de-li"),_T("German (Liechtenstein)")},
	{_T("de-lu"),_T("German (Luxembourg)")},
	{_T("de"),_T("German (Germany)")},
	{_T("div"),_T("Divehi")},
	{_T("el"),_T("Greek")},
	{_T("en-au"),_T("English (Australia)")},
	{_T("en-bz"),_T("English (Belize)")},
	{_T("en-ca"),_T("English (Canada)")},
	{_T("en-gb"),_T("English (United Kingdom)")},
	{_T("en-ie"),_T("English (Ireland)")},
	{_T("en-jm"),_T("English (Jamaica)")},
	{_T("en-nz"),_T("English (New Zealand)")},
	{_T("en-ph"),_T("English (Philippines)")},
	{_T("en-tt"),_T("English (Trinidad)")},
	{_T("en-us"),_T("English (United States)")},
	{_T("en-za"),_T("English (South Africa)")},
	{_T("en-zw"),_T("English (Zimbabwe)")},
	{_T("en"),_T("English")},
	{_T("es-ar"),_T("Spanish (Argentina)")},
	{_T("es-bo"),_T("Spanish (Bolivia)")},
	{_T("es-cl"),_T("Spanish (Chile)")},
	{_T("es-co"),_T("Spanish (Colombia)")},
	{_T("es-cr"),_T("Spanish (Costa Rica)")},
	{_T("es-do"),_T("Spanish (Dominican Republic)")},
	{_T("es-ec"),_T("Spanish (Ecuador)")},
	{_T("es-gt"),_T("Spanish (Guatemala)")},
	{_T("es-hn"),_T("Spanish (Honduras)")},
	{_T("es-mx"),_T("Spanish (Mexico)")},
	{_T("es-ni"),_T("Spanish (Nicaragua)")},
	{_T("es-pa"),_T("Spanish (Panama)")},
	{_T("es-pe"),_T("Spanish (Peru)")},
	{_T("es-pr"),_T("Spanish (Puerto Rico)")},
	{_T("es-py"),_T("Spanish (Paraguay)")},
	{_T("es-sv"),_T("Spanish (El Salvador)")},
	{_T("es-us"),_T("Spanish (United States)")},
	{_T("es-uy"),_T("Spanish (Uruguay)")},
	{_T("es-ve"),_T("Spanish (Venezuela)")},
	{_T("es"),_T("Spanish")},
	{_T("et"),_T("Estonian")},
	{_T("eu"),_T("Basque")},
	{_T("fa"),_T("Farsi")},
	{_T("fi"),_T("Finnish")},
	{_T("fo"),_T("Faeroese")},
	{_T("fr-be"),_T("French (Belgium)")},
	{_T("fr-ca"),_T("French (Canada)")},
	{_T("fr-ch"),_T("French (Switzerland)")},
	{_T("fr-lu"),_T("French (Luxembourg)")},
	{_T("fr-mc"),_T("French (Monaco)")},
	{_T("fr"),_T("French (France)")},
	{_T("gd"),_T("Gaelic")},
	{_T("gl"),_T("Galician")},
	{_T("gu"),_T("Gujarati")},
	{_T("he"),_T("Hebrew")},
	{_T("hi"),_T("Hindi")},
	{_T("hr"),_T("Croatian")},
	{_T("hu"),_T("Hungarian")},
	{_T("hy"),_T("Armenian")},
	{_T("id"),_T("Indonesian")},
	{_T("is"),_T("Icelandic")},
	{_T("it-ch"),_T("Italian (Switzerland)")},
	{_T("it"),_T("Italian (Italy)")},
	{_T("ja"),_T("Japanese")},
	{_T("ka"),_T("Georgian")},
	{_T("kk"),_T("Kazakh")},
	{_T("kn"),_T("Kannada")},
	{_T("ko"),_T("Korean")},
	{_T("kok"),_T("Konkani")},
	{_T("kz"),_T("Kyrgyz")},
	{_T("lt"),_T("Lithuanian")},
	{_T("lv"),_T("Latvian")},
	{_T("mk"),_T("Macedonian (FYROM)")},
	{_T("ml"),_T("Malayalam")},
	{_T("mn"),_T("Mongolian (Cyrillic)")},
	{_T("mr"),_T("Marathi")},
	{_T("ms"),_T("Malay")},
	{_T("mt"),_T("Maltese")},
	{_T("nb-no"),_T("Norwegian (Bokmal)")},
	{_T("ne"),_T("Nepali (India)")},
	{_T("nl-be"),_T("Dutch (Belgium)")},
	{_T("nl"),_T("Dutch (Netherlands)")},
	{_T("nn-no"),_T("Norwegian (Nynorsk)")},
	{_T("no"),_T("Norwegian (Bokmal)")},
	{_T("or"),_T("Oriya")},
	{_T("pa"),_T("Punjabi")},
	{_T("pl"),_T("Polish")},
	{_T("pt-br"),_T("Portuguese (Brazil)")},
	{_T("pt"),_T("Portuguese (Portugal)")},
	{_T("rm"),_T("Rhaeto-Romanic")},
	{_T("ro-md"),_T("Romanian (Moldova)")},
	{_T("ro"),_T("Romanian")},
	{_T("ru-md"),_T("Russian (Moldova)")},
	{_T("ru"),_T("Russian")},
	{_T("sa"),_T("Sanskrit")},
	{_T("sb"),_T("Sorbian")},
	{_T("sk"),_T("Slovak")},
	{_T("sl"),_T("Slovenian")},
	{_T("sq"),_T("Albanian")},
	{_T("sr"),_T("Serbian")},
	{_T("sv-fi"),_T("Swedish (Finland)")},
	{_T("sv"),_T("Swedish")},
	{_T("sw"),_T("Swahili")},
	{_T("sx"),_T("Sutu")},
	{_T("syr"),_T("Syriac")},
	{_T("ta"),_T("Tamil")},
	{_T("te"),_T("Telugu")},
	{_T("th"),_T("Thai")},
	{_T("tn"),_T("Tswana")},
	{_T("tr"),_T("Turkish")},
	{_T("ts"),_T("Tsonga")},
	{_T("tt"),_T("Tatar")},
	{_T("uk"),_T("Ukrainian")},
	{_T("ur"),_T("Urdu")},
	{_T("uz"),_T("Uzbek")},
	{_T("vi"),_T("Vietnamese")},
	{_T("xh"),_T("Xhosa")},
	{_T("yi"),_T("Yiddish")},
	{_T("zh-cn"),_T("Chinese (China)")},
	{_T("zh-hk"),_T("Chinese (Hong Kong SAR)")},
	{_T("zh-mo"),_T("Chinese (Macao SAR)")},
	{_T("zh-sg"),_T("Chinese (Singapore)")},
	{_T("zh-tw"),_T("Chinese (Taiwan)")},
	{_T("zh"),_T("Chinese")},
	{_T("zu"),_T("Zulu")},
};

#endif//LangIDs_Defined

